version: '2'

services:
  traefik:
    image: traefik:alpine
    ports:
      - '80:80'
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - webtest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./opt/traefik/traefik.toml:/traefik.toml
      - ./opt/traefik/acme.json:/acme.json
  
  web:
    image: httpd:alpine
    deploy:
      replicas: 1
      labels:
        - "traefik.docker.network=webtest"
        - "traefik.enable=true"
        - "traefik.basic.frontend.rule=Host:app.my-awesome-app.org"
        - "traefik.basic.port=9000"
        - "traefik.basic.protocol=http"
        - "traefik.admin.frontend.rule=Host:admin-app.my-awesome-app.org"
        - "traefik.admin.protocol=https"
        - "traefik.admin.port=9443"
    networks:
        - webtest

networks:
  webtest:
    external: true