version: '2'

services:
  traefik:
    image: traefik:alpine
    ports:
      - '80:80'
      - '443:443'
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - webtest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .traefik.toml:/traefik.toml
      - .acme.json:/acme.json
  
  web:
    image: httpd:alpine
    deploy:
      replicas: 1
      labels:
        - "traefik.docker.network=webtest"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:test.habeshaexpress.com"
        - "traefik.protocol=https"
        - "traefik.port=80"
    networks:
        - webtest

networks:
  webtest:
    external: true