version: '3.4'


networks:
  webgateway:
    external: true
    
services:
  traefik:
    image: traefik:alpine
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    deploy:
      labels:
        - traefik.frontend.rule=Host:habeshaexpress.com
        - traefik.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .traefik.toml:/traefik.toml
      - .acme.json:/acme.json
    command: >
      --docker
      --docker.swarmmode
      --docker.watch
      --web
      --logLevel=INFO
    networks:
      - webgateway