services:
  proxy:
    image: traefik:1.4-alpine
    command: --web --docker --docker.domain=docker.localhost
    networks:
      - traefik
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  apache:
    image: httpd:alpine
    labels:
      - "traefik.frontend.rule=Host:apache.localhost"
    networks:
      - traefik
  nginx:
    image: nginx:alpine
    labels:
      - "traefik.frontend.rule=Host:nginx.localhost"
    networks:
      - traefik

networks:
  traefik:
    external: true