version: "3"
services:
  traefik:
    image: traefik:alpine
    command:
      # - "--api"
      # - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      # - "--entrypoints=Name:https Address::443 TLS"
      # - "--defaultentrypoints=http,https"
      # - "--acme"
      # - "--acme.storage=/etc/traefik/acme/acme.json"
      # - "--acme.entryPoint=https"
      # - "--acme.httpChallenge.entryPoint=http"
      # - "--acme.onHostRule=true"
      # - "--acme.onDemand=false"
      # - "--acme.email=contact@mydomain.ca"
      - "--web"
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.domain=habeshaexpress.com"
      - "--docker.watch"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webgateway
      - traefik
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  apache:
    image: httpd:alpine
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.frontend.rule=Host:test.habeshaexpress.com"
    networks:
      - traefik
networks:
  webgateway:
    driver: overlay
    external: true
  traefik:
    driver: overlay