version: "3.4"

services:
  who:
    image: emilevauge/whoami
    container_name: whoami_service
    networks:
      - traefik-net
    labels: 
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:one.worker.com"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
networks:
  traefik-net:
    external: true
    